import 'package:flutter/material.dart';
import '../common/common.dart';
import '../constants/constant.dart';

import 'dart:async';
import 'dart:convert';

import 'package:http/http.dart' as http;
import '../globals.dart' as globals;

class WelcomeCardWidget extends StatelessWidget {
  const WelcomeCardWidget({Key key}) : super(key: key);
// \u2109
  @override
  Widget build(BuildContext context) {
    var randomFact = "Less than 20% of conversational laughter is generated by an actual joke or humourous comment.";
    Timer.run(() async {
      final url = Uri.parse('http://192.168.1.100:8000/api/getsetting/fact');
      http.Response response = await http.get(url, headers: {'Accept': 'application/json'});
      var body = json.decode(response.body);
      if (body['success']) {
        randomFact = body['value'];
      }
      print(response.body);
    });


    return ContentContainer(
      borderRadius: 16,
      child: Container(
        width: MediaQuery.of(context).size.width * .6 - 100,
        height: 180,
        child: Padding(
          padding: const EdgeInsets.only(
            top: 16,
            bottom: 10,
            left: 24,
          ),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Welcome home!',
                style: TextStyle(
                  color: AppColors.white,
                  fontSize: 48,
                  fontWeight: FontWeight.normal,
                  letterSpacing: 1.54,
                ),
              ),
              /*const Text(
                'Welcome Home!',
                style: TextStyle(
                  color: AppColors.description,
                  fontSize: 12,
                  fontWeight: FontWeight.normal,
                  letterSpacing: .64,
                  height: 1.4,
                ),
              ),
              const VerticalSpacer(
                space: 8,
              ),*/
              const VerticalSpacer(space: 2),
              Text(
                'Random fact of the day: $randomFact',
                style: TextStyle(
                  color: AppColors.white,
                  fontSize: 14,
                  fontWeight: FontWeight.normal,
                  letterSpacing: 1.54,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
